config/routes.rb
Hardhathub::Application.routes.draw do
  # https://github.com/basecamp/mail_view#routing
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  devise_for :users, controllers: { sessions: :sessions, confirmations: :confirmations, registrations: :registrations, omniauth_callbacks: :omniauth_callbacks }
  ActiveAdmin.routes(self)

  root to: 'audience_types#index'

  resources :audience_types, only: %i(index show)

  resources :professional_profiles, only: %i(edit update) do
    get '/resume' => 'professional_profiles#resume'
    get '/send_confirmation' => 'professional_profiles#send_confirmation'
    resources :travel_preferences, only: %i(edit update)
    resources :schedule_preferences, only: %i(edit update)
    resources :salary_preferences, only: %i(edit update)
    resources :qualifications, only: %i(edit update)
    resources :work_histories, only: %i(index create update destroy)
    resources :education_histories, only: %i(index create update destroy)
  end

  resources :company_profiles, only: %i(index show)

  resources :get_started

  # hubspot reverse sync calls
  resources :webhook_users, only: %i(create)
  get '/activate/:token' => 'webhook_users#activate', as: :activate
  get '/wizard' => 'webhook_users#register'
  post '/wizard' => 'webhook_users#register_from_post'

  get '/pages/*id' => 'high_voltage/pages#show', as: :page, format: false

  # redirects
  get '*path' => 'application#handle_unknown_url'
end

# == Route Map (Updated 2014-11-25 07:46)
#
#                                        Prefix Verb     URI Pattern                                                                             Controller#Action
#                                                        /mail_view                                                                              MailPreview
#                              new_user_session GET      /users/sign_in(.:format)                                                                sessions#new
#                                  user_session POST     /users/sign_in(.:format)                                                                sessions#create
#                          destroy_user_session DELETE   /users/sign_out(.:format)                                                               sessions#destroy
#                       user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                                                         omniauth_callbacks#passthru {:provider=>/linkedin/}
#                        user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)                                                  omniauth_callbacks#(?-mix:linkedin)
#                                 user_password POST     /users/password(.:format)                                                               devise/passwords#create
#                             new_user_password GET      /users/password/new(.:format)                                                           devise/passwords#new
#                            edit_user_password GET      /users/password/edit(.:format)                                                          devise/passwords#edit
#                                               PATCH    /users/password(.:format)                                                               devise/passwords#update
#                                               PUT      /users/password(.:format)                                                               devise/passwords#update
#                      cancel_user_registration GET      /users/cancel(.:format)                                                                 registrations#cancel
#                             user_registration POST     /users(.:format)                                                                        registrations#create
#                         new_user_registration GET      /users/sign_up(.:format)                                                                registrations#new
#                        edit_user_registration GET      /users/edit(.:format)                                                                   registrations#edit
#                                               PATCH    /users(.:format)                                                                        registrations#update
#                                               PUT      /users(.:format)                                                                        registrations#update
#                                               DELETE   /users(.:format)                                                                        registrations#destroy
#                             user_confirmation POST     /users/confirmation(.:format)                                                           confirmations#create
#                         new_user_confirmation GET      /users/confirmation/new(.:format)                                                       confirmations#new
#                                               GET      /users/confirmation(.:format)                                                           confirmations#show
#                                    admin_root GET      /admin(.:format)                                                                        admin/dashboard#index
#          batch_action_admin_audience_profiles POST     /admin/audience_profiles/batch_action(.:format)                                         admin/audience_profiles#batch_action
#                       admin_audience_profiles GET      /admin/audience_profiles(.:format)                                                      admin/audience_profiles#index
#                                               POST     /admin/audience_profiles(.:format)                                                      admin/audience_profiles#create
#                    new_admin_audience_profile GET      /admin/audience_profiles/new(.:format)                                                  admin/audience_profiles#new
#                   edit_admin_audience_profile GET      /admin/audience_profiles/:id/edit(.:format)                                             admin/audience_profiles#edit
#                        admin_audience_profile GET      /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#show
#                                               PATCH    /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#update
#                                               PUT      /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#update
#                                               DELETE   /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#destroy
#             batch_action_admin_audience_types POST     /admin/audience_types/batch_action(.:format)                                            admin/audience_types#batch_action
#                          admin_audience_types GET      /admin/audience_types(.:format)                                                         admin/audience_types#index
#                                               POST     /admin/audience_types(.:format)                                                         admin/audience_types#create
#                       new_admin_audience_type GET      /admin/audience_types/new(.:format)                                                     admin/audience_types#new
#                      edit_admin_audience_type GET      /admin/audience_types/:id/edit(.:format)                                                admin/audience_types#edit
#                           admin_audience_type GET      /admin/audience_types/:id(.:format)                                                     admin/audience_types#show
#                                               PATCH    /admin/audience_types/:id(.:format)                                                     admin/audience_types#update
#                                               PUT      /admin/audience_types/:id(.:format)                                                     admin/audience_types#update
#                                               DELETE   /admin/audience_types/:id(.:format)                                                     admin/audience_types#destroy
#                 batch_action_admin_categories POST     /admin/categories/batch_action(.:format)                                                admin/categories#batch_action
#                              admin_categories GET      /admin/categories(.:format)                                                             admin/categories#index
#                                               POST     /admin/categories(.:format)                                                             admin/categories#create
#                            new_admin_category GET      /admin/categories/new(.:format)                                                         admin/categories#new
#                           edit_admin_category GET      /admin/categories/:id/edit(.:format)                                                    admin/categories#edit
#                                admin_category GET      /admin/categories/:id(.:format)                                                         admin/categories#show
#                                               PATCH    /admin/categories/:id(.:format)                                                         admin/categories#update
#                                               PUT      /admin/categories/:id(.:format)                                                         admin/categories#update

app/controllers/professional_profiles_controller.rb
class ProfessionalProfilesController < ProfessionalController
  before_action :redirect_if_wizard_not_completed, only: :edit

  def edit
    @professional_profile_form = ProfessionalProfileForm.new(current_user.professional_profile)
  end

  def update
    @hubspot_form = HubspotterInterface::ProfileEngagementForm.new(
      current_user, current_user_hubspot_token, current_user_ip)
    @professional_profile_form = ProfessionalProfileForm.new(
      current_user.professional_profile, permitted_params)
    @professional_profile_form.process
    if @professional_profile_form.errors.present?
      flash[:error] = @professional_profile_form.errors.full_messages.to_sentence
    else
      flash[:success] = t("views.professional_profiles.updated")
    end
    redirect_to edit_professional_profile_path(@professional_profile)
  end

  def resume
    if @professional_profile.resume?
      resume = @professional_profile.resume
      download_name = @professional_profile.resume_original_filename
      download_name = download_name.blank? ? resume.path.split("/").last : download_name
      send_data(resume.read, filename: download_name)
    else
      render nothing: true
    end
  end

  def send_confirmation
    flash[:success] = t("devise.confirmations.send_instructions")
    current_user.resend_confirmation_instructions
    redirect_to edit_professional_profile_path(current_user)
  end

  private

  def permitted_params
    engagement_pref_attrs = %i(starting_date
                               term_quick
                               term_small
                               term_large
                               term_permanent
                               term_various
                               other_concerns)

    params.require(:professional_profile_form).permit(
      :status,
      :country,
      :state,
      :city,
      :zip_code,
      :civil,
      :infrastructure,
      :energy,
      :building,
      :petroleum,
      :anything,
      :industry_other,
      :resume,
      :resume_cache,
      :remove_resume,
      :first_name,
      :last_name,
      :email,
      :phone_number,
      :password,
      :password_confirmation,
      role_preference_attributes: [ :audience_type_id ],
      engagement_preference_attributes: engagement_pref_attrs)
  end

  private

  def redirect_if_wizard_not_completed
    step_manager = GetStarted::StepManager.new(current_user)
    redirect_to get_started_path(step_manager.starting_step) unless step_manager.wizard_complete?
  end
end

app/helpers/admin/professional_profile_helper.rb
module Admin::ProfessionalProfileHelper
  include Admin::ProfessionalProfileExporter

  def component_attribute_names(component_class, extras=[])
    do_not_display = %i(id professional_profile_id created_at updated_at)
    names = component_class.attribute_names.map(&:to_sym)
    names.delete_if{|name| do_not_display.include? name }
    names + extras
  end

  def show_panel_for(profile, component_name)
    component = profile.send(component_name)
    panel "#{component.class.model_name.human} Details" do
      component_table_for(component)
    end
  end

  def show_collection_for(profile, collection_name)
    collection = profile.send(collection_name)
    component_class = as_class collection_name
    panel "#{component_class.model_name.human} Details" do
      collection.each { |component| component_table_for(component) }
    end
  end

  def edit_panel_for(form, component_name)
    component_class = as_class component_name
    form.inputs component_class.model_name.human, for: component_name do |f|
      component_attribute_names(component_class).each do |attr|
        opts = input_options component_class, attr
        opts = yield(opts) if block_given?
        f.input attr, opts
      end
    end
  end

  def component_table_for(component)
    component_class = component.class
    attributes_table_for component_class do
      component_attribute_names(component_class).each do |attr|
        if text_attribute?(component_class, attr)
          text_row component, attr
        else
          row(component_class.human_attribute_name(attr)) { component.send(attr) }
        end
      end
    end
  end

  def input_options(model, attribute)
    opts = {}
    opts.merge!(input_html: { class: 'tinymce-editor' }) if text_attribute? model, attribute
    opts.merge!(start_year: Time.now.year - 60, end_year: Time.now.year) if date_attribute? model, attribute
    opts
  end

  def text_attribute?(component_class, attribute)
    attribute_type(component_class, attribute) == :text
  end

  def date_attribute?(component_class, attribute)
    attribute_type(component_class, attribute) == :date
  end

  def attribute_type(component_class, attribute)
    component_class.columns_hash[attribute.to_s].type
  end

  def text_row(component, attr)
    if component.respond_to? attr
      row(attr) { component.send(attr).try :html_safe }
    else
      row attr
    end
  end

  def as_class(component_name)
    component_name.to_s.classify.constantize
  end

end

app/views/professional_profiles/_form_nav.html.haml
=link_to t('next.travel_preferences'), edit_profile_component_path(@professional_profile.travel_preference), class: "link--formNav right"

app/views/professional_profiles/_industry_fields.html.haml
%label.label--standard= t("views.professional_profiles.industry")
%input{type:"checkbox", class:"input--selectAll js-select-all", id: "select-all-industry"}
.labelWrapper
  %label.label--selectAll{for: "select-all-industry"}=t("views.shared.select_all")
- IndustryHelper::TYPES_WITH_ANYTHING.each do |industry|
  .inputWrapper--block
    = form.check_box industry, class: "boolean"
    = form.label ProfessionalProfile.human_attribute_name(industry), for: "professional_profile_form_#{industry}"

app/views/professional_profiles/_resume_upload.html.haml
- resume = @professional_profile.resume if @professional_profile.resume?
- hubspot_resume_url = @professional_profile.hubspot_resume_url
= form.input :resume, input_html:{ data:{analytics: "add-resume"}}, as: :file,  label_html: {class: "label--standard"}
- if resume
  %p= link_to @professional_profile.resume_display_name, professional_profile_resume_path(@professional_profile)
  = form.input :remove_resume, as: :boolean
  = form.input :resume_cache, as: :hidden
- elsif hubspot_resume_url
  %p= link_to @professional_profile.hubspot_resume_filename, hubspot_resume_url

app/views/professional_profiles/_starting_date_fields.html.haml
= form.simple_fields_for :engagement_preference_attributes, @professional_profile_form.engagement_preference do |ep|
  = ep.input :starting_date,
              discard_day: true,
              start_year: Time.now.year,
              placeholder: "Pick a date",
              input_html: {class: "date-picker"},
              label_html: {class: "label--standard"}

app/views/professional_profiles/_term_fields.html.haml
= form.simple_fields_for :engagement_preference_attributes, @professional_profile_form.engagement_preference do |ep|
  %label.label--standard= t("views.engagement_preferences.term_lengths")
  %input{type:"checkbox", class:"input--selectAll js-select-all", id: "select-all-terms"}
  .labelWrapper
    %label.label--selectAll{for: "select-all-terms"}=t("views.shared.select_all")
  = ep.input :term_quick
  = ep.input :term_small
  = ep.input :term_large
  = ep.input :term_permanent
  = ep.input :term_various

app/views/professional_profiles/edit.html.haml
.professionalProfile
  = render partial: '/professional_header', locals: { profile_piece: @professional_profile }

  %section.container
    = render "layouts/profile_sidebar"
    %section.mainContent--form
      %section.formWrapper
        %section.formNav--small
          = render "form_nav"

        %header.formHeader
          %h3.formHeader__title
            =t("views.professional_profiles.nav_title")

          %section.formHeader__action
            = link_to omniauth_authorize_path(current_user, :linkedin, state: current_user), class: "button--linkedinSmall js--buttonWorking" do
              %span.button__icon
              %span.button__text= t('linkedin.connect')
            %span.legal
              = t('linkedin.tooltip.connect')

        %section.formHelp
          %h4=t("views.professional_profiles.help_title")
          %p=t("views.professional_profiles.help_text")

        %section.formHelp
          %h4.formSubhead Email Address
          %p
            %span= current_user.email
            %span
              - if current_user.confirmed?
                Confirmed
              - else
                Not Confirmed -
                = link_to('Click to Resend Confimation Email', professional_profile_send_confirmation_path(current_user))

        %section.formHelp
          %div
            %h4.formSubhead Category
            %p= @professional_profile.category.try(:display_name)
          %div
            %h4.formSubhead Category Functions
            %p= @professional_profile.category_functions.map(&:display_name).to_sentence
          %div
            %h4.formSubhead Projects
            %p= @professional_profile.project_types.map(&:display_name).to_sentence
          %div
            %h4.formSubhead Specialties
            %p= @professional_profile.sub_project_types.map(&:display_name).to_sentence
          %div
            %h4.formSubhead Experience
            %p= @professional_profile.experience
          %div
            %h4.formSubhead Authorization
            %p= @professional_profile.authorization
          - unless @professional_profile.authorization
            %div
              %h4.formSubhead Authorization Details
              %p= @professional_profile.authorization_details
          %div
            %h4.formSubhead Desired Locations
            %p= @professional_profile.metro_areas.map(&:area_name).to_sentence



        %section.formEntry
          = simple_form_for @professional_profile_form, url: professional_profile_url, method: :patch, html: { multipart: true, class: 'js-dirty-check', data: {analytics: "submit-professional" } } do |f|
            %section.formBlock
              %section.formBlock__section--full
                = f.input :status, as: :radio_buttons,
                          wrapper_html: {class: "inputWrapper--block"},
                          label_html: {class: "label--standard"}

              %section.formBlock
                %section.formBlock__section--half.hide
                  = render partial: 'starting_date_fields', locals: { form: f }

              %section.formBlock__section--full
                = render partial: 'industry_fields', locals: { form: f }

              %section.formBlock__section--full
                = f.input :industry_other, label: ProfessionalProfile.human_attribute_name(:industry_other),
                          label_html: {class: "label--standard"}

              = f.simple_fields_for :role_preference_attributes, @professional_profile_form.role_preference do |role_preference|
                %section.formblock__section-full
                  = role_preference.input :audience_type_id,
                    as: :select,
                    collection: AudienceType.all,
                    wrapper_html: {class: "inputWrapper--half"},
                    label_html: {class: "label--standard"}

              %section.formBlock__section--half
                = render partial: 'term_fields', locals: { form: f }

              = f.simple_fields_for :engagement_preference_attributes, @professional_profile_form.engagement_preference do |ep|
                %section.formBlock__section--full
                  = ep.input :other_concerns,
                              as: :text,
                              label_html: {class: "label--standard"}

              %section.formBlock__section--full
                %h4.formSubhead Personal Information

                = f.input :first_name,
                          wrapper_html: {class: "inputWrapper--half"},
                          label_html: {class: "label--standard"}

                = f.input :last_name,
                          wrapper_html: {class: "inputWrapper--half inputWrapper--omega"},
                          label_html: {class: "label--standard"}

                = f.input :phone_number,
                          input_html: {value: number_to_phone(current_user.phone_number)},
                          wrapper_html: {class: "inputWrapper--half"},
                          label_html: {class: "label--standard"}

                = f.input :city,
                          wrapper_html: {class: "inputWrapper--half"},
                          label_html: {class: "label--standard"}

                = f.input :state, as: :select, collection: subregions_list,
                          wrapper_html: {class: "inputWrapper--half inputWrapper--omega"},
                          label_html: {class: "label--standard"}

                = f.input :zip_code,
                          wrapper_html: {class: "inputWrapper--half"},
                          label_html: {class: "label--standard"}

                = f.input :country, as: :select, collection: countries_list,
                          wrapper_html: {class: "inputWrapper--half inputWrapper--omega"},
                          label_html: {class: "label--standard"}



            %section.formBlock
              %section.formBlock__section--full
                = render partial: 'resume_upload', locals: { form: f }

            %section.formBlock
              %section.formBlock__section--action
                = f.submit t("views.professional_profiles.submit"), class: "button--update"

        %section.formBlock
          %section.formBlock__section--action
            = render "form_nav"