config/routes.rb
Hardhathub::Application.routes.draw do
  # https://github.com/basecamp/mail_view#routing
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  devise_for :users, controllers: { sessions: :sessions, confirmations: :confirmations, registrations: :registrations, omniauth_callbacks: :omniauth_callbacks }
  ActiveAdmin.routes(self)

  root to: 'audience_types#index'

  resources :audience_types, only: %i(index show)

  resources :professional_profiles, only: %i(edit update) do
    get '/resume' => 'professional_profiles#resume'
    get '/send_confirmation' => 'professional_profiles#send_confirmation'
    resources :travel_preferences, only: %i(edit update)
    resources :schedule_preferences, only: %i(edit update)
    resources :salary_preferences, only: %i(edit update)
    resources :qualifications, only: %i(edit update)
    resources :work_histories, only: %i(index create update destroy)
    resources :education_histories, only: %i(index create update destroy)
  end

  resources :company_profiles, only: %i(index show)

  resources :get_started

  # hubspot reverse sync calls
  resources :webhook_users, only: %i(create)
  get '/activate/:token' => 'webhook_users#activate', as: :activate
  get '/wizard' => 'webhook_users#register'
  post '/wizard' => 'webhook_users#register_from_post'

  get '/pages/*id' => 'high_voltage/pages#show', as: :page, format: false

  # redirects
  get '*path' => 'application#handle_unknown_url'
end

# == Route Map (Updated 2014-11-25 07:46)
#
#                                        Prefix Verb     URI Pattern                                                                             Controller#Action
#                                                        /mail_view                                                                              MailPreview
#                              new_user_session GET      /users/sign_in(.:format)                                                                sessions#new
#                                  user_session POST     /users/sign_in(.:format)                                                                sessions#create
#                          destroy_user_session DELETE   /users/sign_out(.:format)                                                               sessions#destroy
#                       user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                                                         omniauth_callbacks#passthru {:provider=>/linkedin/}
#                        user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)                                                  omniauth_callbacks#(?-mix:linkedin)
#                                 user_password POST     /users/password(.:format)                                                               devise/passwords#create
#                             new_user_password GET      /users/password/new(.:format)                                                           devise/passwords#new
#                            edit_user_password GET      /users/password/edit(.:format)                                                          devise/passwords#edit
#                                               PATCH    /users/password(.:format)                                                               devise/passwords#update
#                                               PUT      /users/password(.:format)                                                               devise/passwords#update
#                      cancel_user_registration GET      /users/cancel(.:format)                                                                 registrations#cancel
#                             user_registration POST     /users(.:format)                                                                        registrations#create
#                         new_user_registration GET      /users/sign_up(.:format)                                                                registrations#new
#                        edit_user_registration GET      /users/edit(.:format)                                                                   registrations#edit
#                                               PATCH    /users(.:format)                                                                        registrations#update
#                                               PUT      /users(.:format)                                                                        registrations#update
#                                               DELETE   /users(.:format)                                                                        registrations#destroy
#                             user_confirmation POST     /users/confirmation(.:format)                                                           confirmations#create
#                         new_user_confirmation GET      /users/confirmation/new(.:format)                                                       confirmations#new
#                                               GET      /users/confirmation(.:format)                                                           confirmations#show
#                                    admin_root GET      /admin(.:format)                                                                        admin/dashboard#index
#          batch_action_admin_audience_profiles POST     /admin/audience_profiles/batch_action(.:format)                                         admin/audience_profiles#batch_action
#                       admin_audience_profiles GET      /admin/audience_profiles(.:format)                                                      admin/audience_profiles#index
#                                               POST     /admin/audience_profiles(.:format)                                                      admin/audience_profiles#create
#                    new_admin_audience_profile GET      /admin/audience_profiles/new(.:format)                                                  admin/audience_profiles#new
#                   edit_admin_audience_profile GET      /admin/audience_profiles/:id/edit(.:format)                                             admin/audience_profiles#edit
#                        admin_audience_profile GET      /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#show
#                                               PATCH    /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#update
#                                               PUT      /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#update
#                                               DELETE   /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#destroy
#             batch_action_admin_audience_types POST     /admin/audience_types/batch_action(.:format)                                            admin/audience_types#batch_action
#                          admin_audience_types GET      /admin/audience_types(.:format)                                                         admin/audience_types#index
#                                               POST     /admin/audience_types(.:format)                                                         admin/audience_types#create
#                       new_admin_audience_type GET      /admin/audience_types/new(.:format)                                                     admin/audience_types#new
#                      edit_admin_audience_type GET      /admin/audience_types/:id/edit(.:format)                                                admin/audience_types#edit
#                           admin_audience_type GET      /admin/audience_types/:id(.:format)                                                     admin/audience_types#show
#                                               PATCH    /admin/audience_types/:id(.:format)                                                     admin/audience_types#update
#                                               PUT      /admin/audience_types/:id(.:format)                                                     admin/audience_types#update
#                                               DELETE   /admin/audience_types/:id(.:format)                                                     admin/audience_types#destroy
#                 batch_action_admin_categories POST     /admin/categories/batch_action(.:format)                                                admin/categories#batch_action
#                              admin_categories GET      /admin/categories(.:format)                                                             admin/categories#index
#                                               POST     /admin/categories(.:format)                                                             admin/categories#create
#                            new_admin_category GET      /admin/categories/new(.:format)                                                         admin/categories#new
#                           edit_admin_category GET      /admin/categories/:id/edit(.:format)                                                    admin/categories#edit
#                                admin_category GET      /admin/categories/:id(.:format)                                                         admin/categories#show
#                                               PATCH    /admin/categories/:id(.:format)                                                         admin/categories#update
#                                               PUT      /admin/categories/:id(.:format)                                                         admin/categories#update

app/models/professional/education_history.rb
class EducationHistory < ActiveRecord::Base
  extend Enumerize
  include ProfessionalProfileComponent
  include ProgressTracking

  belongs_to :professional_profile

  acts_as_taggable_on :concentrations

  ACHIEVEMENT_LEVELS = %i(high_school associates bachelors masters jd phd)

  def self.from_linkedin(history)
    options = {}
    options[:graduation_date] = Date.new(history.endDate.year) if history.endDate
    options[:institution] = history.schoolName
    options[:achievement_level] = history.degree
    options[:concentration_list] = history.fieldOfStudy
    create(options)
  end

  def progress_conditions
    [achievement_level.present?,
        graduation_date.present?,
        institution.present?,
        concentrations.present?]
  end

  def to_s
    desc = []
    desc << "#{achievement_level} degree" if achievement_level
    desc << "from #{institution}" if institution
    desc << "in #{concentration_list.join(', ')}" if concentration_list.present?
    desc << "(#{graduation_date.to_date.strftime('%B %Y')})" if graduation_date
    desc.join ' '
  end
end

# == Schema Information
#
# Table name: education_histories
#
#  id                      :integer          not null, primary key
#  professional_profile_id :integer          not null
#  achievement_level       :string(255)
#  graduation_date         :date
#  created_at              :datetime
#  updated_at              :datetime
#  institution             :string(255)
#
# Indexes
#
#  index_education_histories_on_professional_profile_id  (professional_profile_id)
#

app/controllers/education_histories_controller.rb
class EducationHistoriesController < ProfessionalController

  # Skip because resource loading because CanCan does not
  # play nice with InheritedResources' collection loading.
  # https://github.com/ryanb/cancan/wiki/Inherited-Resources
  skip_load_resource
  after_filter :submit_hubspot_form, only: [:update, :destroy]

  def create
    @professional_profile.education_histories.create!(build_resource_params)
    redirect_to professional_profile_education_histories_path
  end

  def update
    resource.concentration_list = params[:education_history][:concentration_list]
    super do |format|
      format.html { redirect_to professional_profile_education_histories_path }
    end
  end

  def destroy
    super do |format|
      format.html { redirect_to professional_profile_education_histories_path }
    end
  end

  def submit_hubspot_form
    @hubspot_form = HubspotterInterface::ProfileEducationForm.new(current_user,
      current_user_hubspot_token, current_user_ip)
    super
  end

  private

  def resource
    @education_history ||= current_user.professional_profile.education_histories.find(params[:id])
  end

  def collection
    @education_histories ||= current_user.professional_profile.education_histories.order(:created_at)
  end

  def build_resource_params
    [params.fetch(:education_history, {}).permit(%i(
      achievement_level
      graduation_date
      institution
      collection_list ))]
  end
end

app/helpers/education_history_helper.rb
module EducationHistoryHelper
  def concentration_options
    ActsAsTaggableOn::Tag.concentrations.pluck(:name).sort
  end
end

app/views/education_histories/_form_nav.html.haml
=link_to t('back.qualifications'), edit_profile_component_path(@professional_profile.qualification), class: "link--formNav left"
=link_to t('next.work_histories'), professional_profile_work_histories_path(@professional_profile), class: "link--formNav right"

app/views/education_histories/index.html.haml
.professionalProfile
  = render partial: '/professional_header', locals: { profile_piece: @professional_profile }

  %section.container
    = render "layouts/profile_sidebar"
    %section.mainContent--form
      %section.formWrapper
        %section.formNav--small
          = render "form_nav"
        %header.formHeader
          %h3.formHeader__title
            =t('views.education_histories.nav_title')
          %section.formHeader__action
            = link_to omniauth_authorize_path(current_user, :linkedin, state: current_user, limit_to: "education"), class: "button--linkedinSmall js--buttonWorking" do
              %span.button__icon
              %span.button__text= t('linkedin.import')
            %span.legal
              = t('linkedin.tooltip.import')

        %section.formHelp
          %h4=t("views.education_histories.help_title")
          %p=t("views.education_histories.help_text")

        %section.formEntry
          = simple_form_for EducationHistory.new, url: professional_profile_education_histories_path, html: { class: 'js-dirty-check', data: {analytics: "submit-education"}  } do |f|
            %section.formBlock
              %section.formBlock__section--full
                = f.input :institution,
                  label_html: {class: "label--standard"},
                  wrapper_html: {class: "inputWrapper--quarter"}
                = f.input :achievement_level,
                  label_html: {class: "label--standard"},
                  wrapper_html: {class: "inputWrapper--quarter"}
                = f.input :graduation_date,
                  order: [:month, :year],
                  discard_day: true,
                  start_year: Time.now.year - 60,
                  end_year: Time.now.year,
                  label_html: {class: "label--standard"},
                  wrapper_html: {class: "inputWrapper--quarter"},
                  input_html: {class: "date-picker inputWrapper--inner"}
                = f.input :concentration_list, collection: concentration_options,
                  wrapper_html: {class: "inputWrapper--quarter"},
                  input_html: {multiple: true, class: 'js-chosen', data: { placeholder: t("views.education_histories.chosen_placeholder") }},
                  label_html: {class: "label--standard"}

            %section.formBlock__save
              %section.formBlock__section--action
                = f.submit t("views.education_histories.add_entry"), class: "button--small"

        %section.formBlock__section--full
          -@professional_profile.education_histories.each do |eh|
            .historyEntry
              %section.historyEntry__section
                %strong=eh.institution
              %section.historyEntry__section
                %span=eh.achievement_level
                %span=eh.concentrations.first
              %section.historyEntry__section.text-right=eh.graduation_date.try(:year)
              %section.historyEntry__section.text-right=link_to t("views.education_histories.delete_entry"),
                professional_profile_education_history_path(@professional_profile, eh), class: "link--delete", method: :delete
      %section.formBlock
        %section.formBlock__section--action
          = render "form_nav"