config/routes.rb
Hardhathub::Application.routes.draw do
  # https://github.com/basecamp/mail_view#routing
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  devise_for :users, controllers: { sessions: :sessions, confirmations: :confirmations, registrations: :registrations, omniauth_callbacks: :omniauth_callbacks }
  ActiveAdmin.routes(self)

  root to: 'audience_types#index'

  resources :audience_types, only: %i(index show)

  resources :professional_profiles, only: %i(edit update) do
    get '/resume' => 'professional_profiles#resume'
    get '/send_confirmation' => 'professional_profiles#send_confirmation'
    resources :travel_preferences, only: %i(edit update)
    resources :schedule_preferences, only: %i(edit update)
    resources :salary_preferences, only: %i(edit update)
    resources :qualifications, only: %i(edit update)
    resources :work_histories, only: %i(index create update destroy)
    resources :education_histories, only: %i(index create update destroy)
  end

  resources :company_profiles, only: %i(index show)

  resources :get_started

  # hubspot reverse sync calls
  resources :webhook_users, only: %i(create)
  get '/activate/:token' => 'webhook_users#activate', as: :activate
  get '/wizard' => 'webhook_users#register'
  post '/wizard' => 'webhook_users#register_from_post'

  get '/pages/*id' => 'high_voltage/pages#show', as: :page, format: false

  # redirects
  get '*path' => 'application#handle_unknown_url'
end

# == Route Map (Updated 2014-11-25 07:46)
#
#                                        Prefix Verb     URI Pattern                                                                             Controller#Action
#                                                        /mail_view                                                                              MailPreview
#                              new_user_session GET      /users/sign_in(.:format)                                                                sessions#new
#                                  user_session POST     /users/sign_in(.:format)                                                                sessions#create
#                          destroy_user_session DELETE   /users/sign_out(.:format)                                                               sessions#destroy
#                       user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                                                         omniauth_callbacks#passthru {:provider=>/linkedin/}
#                        user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)                                                  omniauth_callbacks#(?-mix:linkedin)
#                                 user_password POST     /users/password(.:format)                                                               devise/passwords#create
#                             new_user_password GET      /users/password/new(.:format)                                                           devise/passwords#new
#                            edit_user_password GET      /users/password/edit(.:format)                                                          devise/passwords#edit
#                                               PATCH    /users/password(.:format)                                                               devise/passwords#update
#                                               PUT      /users/password(.:format)                                                               devise/passwords#update
#                      cancel_user_registration GET      /users/cancel(.:format)                                                                 registrations#cancel
#                             user_registration POST     /users(.:format)                                                                        registrations#create
#                         new_user_registration GET      /users/sign_up(.:format)                                                                registrations#new
#                        edit_user_registration GET      /users/edit(.:format)                                                                   registrations#edit
#                                               PATCH    /users(.:format)                                                                        registrations#update
#                                               PUT      /users(.:format)                                                                        registrations#update
#                                               DELETE   /users(.:format)                                                                        registrations#destroy
#                             user_confirmation POST     /users/confirmation(.:format)                                                           confirmations#create
#                         new_user_confirmation GET      /users/confirmation/new(.:format)                                                       confirmations#new
#                                               GET      /users/confirmation(.:format)                                                           confirmations#show
#                                    admin_root GET      /admin(.:format)                                                                        admin/dashboard#index
#          batch_action_admin_audience_profiles POST     /admin/audience_profiles/batch_action(.:format)                                         admin/audience_profiles#batch_action
#                       admin_audience_profiles GET      /admin/audience_profiles(.:format)                                                      admin/audience_profiles#index
#                                               POST     /admin/audience_profiles(.:format)                                                      admin/audience_profiles#create
#                    new_admin_audience_profile GET      /admin/audience_profiles/new(.:format)                                                  admin/audience_profiles#new
#                   edit_admin_audience_profile GET      /admin/audience_profiles/:id/edit(.:format)                                             admin/audience_profiles#edit
#                        admin_audience_profile GET      /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#show
#                                               PATCH    /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#update
#                                               PUT      /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#update
#                                               DELETE   /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#destroy
#             batch_action_admin_audience_types POST     /admin/audience_types/batch_action(.:format)                                            admin/audience_types#batch_action
#                          admin_audience_types GET      /admin/audience_types(.:format)                                                         admin/audience_types#index
#                                               POST     /admin/audience_types(.:format)                                                         admin/audience_types#create
#                       new_admin_audience_type GET      /admin/audience_types/new(.:format)                                                     admin/audience_types#new
#                      edit_admin_audience_type GET      /admin/audience_types/:id/edit(.:format)                                                admin/audience_types#edit
#                           admin_audience_type GET      /admin/audience_types/:id(.:format)                                                     admin/audience_types#show
#                                               PATCH    /admin/audience_types/:id(.:format)                                                     admin/audience_types#update
#                                               PUT      /admin/audience_types/:id(.:format)                                                     admin/audience_types#update
#                                               DELETE   /admin/audience_types/:id(.:format)                                                     admin/audience_types#destroy
#                 batch_action_admin_categories POST     /admin/categories/batch_action(.:format)                                                admin/categories#batch_action
#                              admin_categories GET      /admin/categories(.:format)                                                             admin/categories#index
#                                               POST     /admin/categories(.:format)                                                             admin/categories#create
#                            new_admin_category GET      /admin/categories/new(.:format)                                                         admin/categories#new
#                           edit_admin_category GET      /admin/categories/:id/edit(.:format)                                                    admin/categories#edit
#                                admin_category GET      /admin/categories/:id(.:format)                                                         admin/categories#show
#                                               PATCH    /admin/categories/:id(.:format)                                                         admin/categories#update
#                                               PUT      /admin/categories/:id(.:format)                                                         admin/categories#update

app/controllers/audience_types_controller.rb
class AudienceTypesController < ApplicationController
  def index
    @audience_types = AudienceType.published.positioned
    @featured_companies = CompanyProfile.featured
  end

  def show
    @audience_type = AudienceType.published.friendly.find(params[:id])
    @user_registration_form = UserRegistrationForm.new
    @featured_audience_profiles = AudienceProfile.published.featured.where(audience_type: @audience_type)
    @unfeatured_audience_profiles = AudienceProfile.published.unfeatured.where(audience_type: @audience_type)
    @featured_companies = CompanyProfile.consulting_partners_of_type(@audience_type.id)
  end

end

app/views/audience_types/_audience_profile.html.haml
%li.profileList__item
  .item__imageContainer
    = image_tag audience_profile.primary_image, class:"item__profileImage"
    = link_to 'Hire me', company_profiles_path, class: "button--tiny item__profileButton"
  .item__detailContainer
    %h5.item__profileName= audience_profile.title
    %ul.tagList.less
      - audience_profile.all_tags.take(3).each do |skill|
        %li.tagList__item= skill
      - if audience_profile.all_tags.size > 3
        %li.item__more More...
    %ul.tagList.hide.more
      - audience_profile.all_tags.each do |skill|
        %li.tagList__item= skill
      %li.item__less Less...
    %p.item__profileDetail= truncate(audience_profile.bio, length: 130)

app/views/audience_types/_audience_type.html.haml
%li.imageList__item
  = link_to audience_type, class:"item__image" do
    = image_tag audience_type.primary_image
  = link_to audience_type.name, audience_type, class: "item__title"

app/views/audience_types/_audience_type_detail.html.haml
%li.imageList__item--large
  = link_to company_profiles_path, class:"item__image" do
    = image_tag audience_type_detail.primary_image
  = link_to audience_type_detail.name, "#", class: "item__title"
  %p.item__detail= audience_type_detail.description
  = link_to text('audience_profile.button', scope: 'views.audience_types.show'), company_profiles_path, class: "button--small item__button"

app/views/audience_types/_featured_audience_profile.html.haml
%li.imageList__item--large
  = link_to company_profiles_path, class:"item__image" do
    = image_tag featured_audience_profile.primary_image
  = link_to featured_audience_profile.title, company_profiles_path, class: "item__title"
  %p.item__detail= truncate(featured_audience_profile.bio, length: 210)
  - unless @audience_type.is_project_manager? || @audience_type.is_facility_manager?
    = link_to text('audience_profile.button', scope: 'views.audience_types.show'), company_profiles_path, class: "button--small item__button"

app/views/audience_types/_featured_partner.haml
= link_to featured_partner, class: "companyLogo js--filter__item", data: industries_to_data_value(featured_partner.industries) do
  = image_tag(featured_partner.logo)

app/views/audience_types/index.html.haml
= content_for :hero do
  %section.hero
    %h2.hero__headline= text('hero.headline')
    = link_to text('hero.button'), new_user_registration_path, class: 'button--large hero__button', data: {analytics: 'click-get-started'}

%aside.heroSupplement
  %ol.heroSupplement__list

    - t('views.pages.homepage.steps').keys.each_with_index do |step, i|
      %li.heroSupplement__item
        %figure.heroSupplement__listNumber= i + 1
        %figcaption.heroSupplement__listContent= text("steps.#{step}")

%section.contentSection
  .contentSection__content
    %h2.contentSection__heading= text('employer_partners.title')
    %hr.contentSection__hr
    %p.contentSection__lead= text('employer_partners.text')

  -# TODO: Wire up categories from company listings
  .contentSection__filters
    %ul.filters__list.js--filter
      %li.filters__item
        %a.filters__link.is-active{:href => "#all"} All
      - IndustryHelper::TYPES.each do |industry|
        %li.filters__item
          %a.filters__link{:href => "##{industry}"}
            = I18n.t industry, scope: 'enumerize.industry_types'

    %section.companies
      = render partial: "featured_partner", collection: @featured_companies

%section.contentSection--alt
  .contentSection__content
    %h2.contentSection__heading= text('professional_partners.title')
    %hr.contentSection__hr
    %p.contentSection__lead= text('professional_partners.text')

  %ul.contentSection__imageList
    = render partial: "audience_type", collection: @audience_types

  %section.contentSection__action
    %p.action__message
      = html('action.message', inline: true)
    = link_to text('action.button'), new_user_registration_path, class: 'button--large action__button', data: {analytics: 'click-get-started'}
    %p.action__message--secondary= text('action.message_secondary')

%section.contentSection
  .contentSection__content
    %h2.contentSection__heading= text('about.title')
    %hr.contentSection__hr
    %p.contentSection__lead= text('about.lead')
    %p.contentSection__detail--split= text('about.detail')

app/views/audience_types/show.html.haml
= content_for :hero do
  %section.hero
    - if @audience_type.is_facility_manager? || @audience_type.is_project_manager?
      = render partial: "landing_page_partials/hero_landing_page_test"
    -else
      %h2.hero__headline
        = @audience_type.name
      %hr.hero__hr
      %p.hero__detail
        = @audience_type.description
      = link_to text('hero.button'), new_user_registration_path, class: 'button--large hero__button', data: {analytics: 'click-get-started'}

- if @featured_audience_profiles.present?
  %section.contentSection--alt
    .contentSection__content
      %h2.contentSection__heading= text('featured_profiles.title')
      %hr.contentSection__hr
      %p.contentSection__lead= text('featured_profiles.text')

    -# DESIGN: add hover, active states to links
    %ul.contentSection__imageList
      = render partial: "featured_audience_profile", collection: @featured_audience_profiles

- if @unfeatured_audience_profiles.present?
  %section.contentSection
    .contentSection__content
      %h2.contentSection__heading= text('featured_consultants.title')
      %hr.contentSection__hr
      %p.contentSection__lead= text('featured_consultants.text')
    %ul.contentSection__profileList
      = render partial: "audience_profile", collection: @unfeatured_audience_profiles

    %section.contentSection__action
      %p.action__message
        = html('action.message', inline: true)
      = link_to text('action.button'), new_user_registration_path, class: 'button--large action__button', data: {analytics: 'click-get-started'}
      %p.action__message--secondary= text('action.message_secondary')

- if @featured_companies.present?
  %section.contentSection--alt
    .contentSection__content#featured_companies
      %h2.contentSection__heading= text('featured_consulting_partners.title')
      %hr.contentSection__hr
      %p.contentSection__lead= text('featured_consulting_partners.text')

    .contentSection__filters
      %section.companies
        = render partial: "featured_partner", collection: @featured_companies

- if @audience_type.is_project_manager? || @audience_type.is_facility_manager?
  = render partial: "landing_page_partials/audience_profile_lp_test_form"

%section.contentSection
  .contentSection__content
    - if @audience_type.is_project_manager? || @audience_type.is_facility_manager?
      = render partial: "landing_page_partials/content_landing_page_test"
    - else
      %h2.contentSection__heading
        = text('about.title', audience: @audience_type.name)
      %hr.contentSection__hr
      %p.contentSection__lead= text('about.lead')
      %p.contentSection__detail--split
        = @audience_type.more_about
      = link_to text('about.button'), company_profiles_path, class: 'button--large action__button'