config/routes.rb
Hardhathub::Application.routes.draw do
  # https://github.com/basecamp/mail_view#routing
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  devise_for :users, controllers: { sessions: :sessions, confirmations: :confirmations, registrations: :registrations, omniauth_callbacks: :omniauth_callbacks }
  ActiveAdmin.routes(self)

  root to: 'audience_types#index'

  resources :audience_types, only: %i(index show)

  resources :professional_profiles, only: %i(edit update) do
    get '/resume' => 'professional_profiles#resume'
    get '/send_confirmation' => 'professional_profiles#send_confirmation'
    resources :travel_preferences, only: %i(edit update)
    resources :schedule_preferences, only: %i(edit update)
    resources :salary_preferences, only: %i(edit update)
    resources :qualifications, only: %i(edit update)
    resources :work_histories, only: %i(index create update destroy)
    resources :education_histories, only: %i(index create update destroy)
  end

  resources :company_profiles, only: %i(index show)

  resources :get_started

  # hubspot reverse sync calls
  resources :webhook_users, only: %i(create)
  get '/activate/:token' => 'webhook_users#activate', as: :activate
  get '/wizard' => 'webhook_users#register'
  post '/wizard' => 'webhook_users#register_from_post'

  get '/pages/*id' => 'high_voltage/pages#show', as: :page, format: false

  # redirects
  get '*path' => 'application#handle_unknown_url'
end

# == Route Map (Updated 2014-11-25 07:46)
#
#                                        Prefix Verb     URI Pattern                                                                             Controller#Action
#                                                        /mail_view                                                                              MailPreview
#                              new_user_session GET      /users/sign_in(.:format)                                                                sessions#new
#                                  user_session POST     /users/sign_in(.:format)                                                                sessions#create
#                          destroy_user_session DELETE   /users/sign_out(.:format)                                                               sessions#destroy
#                       user_omniauth_authorize GET|POST /users/auth/:provider(.:format)                                                         omniauth_callbacks#passthru {:provider=>/linkedin/}
#                        user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)                                                  omniauth_callbacks#(?-mix:linkedin)
#                                 user_password POST     /users/password(.:format)                                                               devise/passwords#create
#                             new_user_password GET      /users/password/new(.:format)                                                           devise/passwords#new
#                            edit_user_password GET      /users/password/edit(.:format)                                                          devise/passwords#edit
#                                               PATCH    /users/password(.:format)                                                               devise/passwords#update
#                                               PUT      /users/password(.:format)                                                               devise/passwords#update
#                      cancel_user_registration GET      /users/cancel(.:format)                                                                 registrations#cancel
#                             user_registration POST     /users(.:format)                                                                        registrations#create
#                         new_user_registration GET      /users/sign_up(.:format)                                                                registrations#new
#                        edit_user_registration GET      /users/edit(.:format)                                                                   registrations#edit
#                                               PATCH    /users(.:format)                                                                        registrations#update
#                                               PUT      /users(.:format)                                                                        registrations#update
#                                               DELETE   /users(.:format)                                                                        registrations#destroy
#                             user_confirmation POST     /users/confirmation(.:format)                                                           confirmations#create
#                         new_user_confirmation GET      /users/confirmation/new(.:format)                                                       confirmations#new
#                                               GET      /users/confirmation(.:format)                                                           confirmations#show
#                                    admin_root GET      /admin(.:format)                                                                        admin/dashboard#index
#          batch_action_admin_audience_profiles POST     /admin/audience_profiles/batch_action(.:format)                                         admin/audience_profiles#batch_action
#                       admin_audience_profiles GET      /admin/audience_profiles(.:format)                                                      admin/audience_profiles#index
#                                               POST     /admin/audience_profiles(.:format)                                                      admin/audience_profiles#create
#                    new_admin_audience_profile GET      /admin/audience_profiles/new(.:format)                                                  admin/audience_profiles#new
#                   edit_admin_audience_profile GET      /admin/audience_profiles/:id/edit(.:format)                                             admin/audience_profiles#edit
#                        admin_audience_profile GET      /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#show
#                                               PATCH    /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#update
#                                               PUT      /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#update
#                                               DELETE   /admin/audience_profiles/:id(.:format)                                                  admin/audience_profiles#destroy
#             batch_action_admin_audience_types POST     /admin/audience_types/batch_action(.:format)                                            admin/audience_types#batch_action
#                          admin_audience_types GET      /admin/audience_types(.:format)                                                         admin/audience_types#index
#                                               POST     /admin/audience_types(.:format)                                                         admin/audience_types#create
#                       new_admin_audience_type GET      /admin/audience_types/new(.:format)                                                     admin/audience_types#new
#                      edit_admin_audience_type GET      /admin/audience_types/:id/edit(.:format)                                                admin/audience_types#edit
#                           admin_audience_type GET      /admin/audience_types/:id(.:format)                                                     admin/audience_types#show
#                                               PATCH    /admin/audience_types/:id(.:format)                                                     admin/audience_types#update
#                                               PUT      /admin/audience_types/:id(.:format)                                                     admin/audience_types#update
#                                               DELETE   /admin/audience_types/:id(.:format)                                                     admin/audience_types#destroy
#                 batch_action_admin_categories POST     /admin/categories/batch_action(.:format)                                                admin/categories#batch_action
#                              admin_categories GET      /admin/categories(.:format)                                                             admin/categories#index
#                                               POST     /admin/categories(.:format)                                                             admin/categories#create
#                            new_admin_category GET      /admin/categories/new(.:format)                                                         admin/categories#new
#                           edit_admin_category GET      /admin/categories/:id/edit(.:format)                                                    admin/categories#edit
#                                admin_category GET      /admin/categories/:id(.:format)                                                         admin/categories#show
#                                               PATCH    /admin/categories/:id(.:format)                                                         admin/categories#update
#                                               PUT      /admin/categories/:id(.:format)                                                         admin/categories#update

app/models/professional/work_history.rb
class WorkHistory < ActiveRecord::Base
  extend Enumerize
  include ProfessionalProfileComponent
  include ProgressTracking

  belongs_to :professional_profile

  def self.from_linkedin(history)
    options = {}
    options[:from_date] = Date.new(history.startDate.year, (history.startDate.month || 1)) if history.startDate
    options[:to_date]   = Date.new(history.endDate.year, (history.endDate.month || 1)) if history.endDate
    options[:company]   = history.company.try(:name)
    options[:industry]  = UserLinkedinClient.industry_for_company(history.company.try(:id))
    options[:position]  = history.title
    options[:current]   = history.isCurrent
    options[:summary]   = history.summary
    create(options)
  end

  def progress_conditions
    [company.present?,
        industry.present? || industry_other.present?,
        from_date.present? && to_date.present?,
        position.present?]
  end

  def to_s
    desc = []
    desc << "Company: #{company}" if company
    desc << "Industry: #{industry_other.presence || industry}" if industry_other || industry
    desc << "Started on: #{I18n.l from_date, format: :short}" if from_date
    desc << "Ended on: #{I18n.l to_date, format: :short}" if to_date
    desc << "Position: #{position}" if position
    desc << "Current? #{I18n.t current ? 'affirmative' : 'negative'}"
    desc << "Summary: #{summary}" if summary.presence
    desc.join ', '
  end
end

# == Schema Information
#
# Table name: work_histories
#
#  id                      :integer          not null, primary key
#  professional_profile_id :integer          not null
#  company                 :string(255)
#  industry                :string(255)      default("anything"), not null
#  industry_other          :string(255)
#  from_date               :date
#  to_date                 :date
#  position                :string(255)
#  summary                 :text
#  created_at              :datetime
#  updated_at              :datetime
#  current                 :boolean
#
# Indexes
#
#  index_work_histories_on_professional_profile_id  (professional_profile_id)
#

app/controllers/work_histories_controller.rb
class WorkHistoriesController < ProfessionalController

  # Skip because resource loading because CanCan does not
  # play nice with InheritedResources' collection loading.
  # https://github.com/ryanb/cancan/wiki/Inherited-Resources
  skip_load_resource
  after_filter :submit_hubspot_form, only: [:update, :destroy]

  def create
    @professional_profile.work_histories.create!(build_resource_params)
    redirect_to professional_profile_work_histories_path
  end

  def update
    super do |format|
      format.html { redirect_to professional_profile_work_histories_path }
    end
  end

  def destroy
    super do |format|
      format.html { redirect_to professional_profile_work_histories_path }
    end
  end

  def submit_hubspot_form
    @hubspot_form = HubspotterInterface::ProfileWorkForm.new(current_user,
      current_user_hubspot_token, current_user_ip)
    super
  end

  private

  def resource
    @work_history ||= current_user.professional_profile.work_histories.find(params[:id])
  end

  def collection
    @work_histories ||= current_user.professional_profile.work_histories.order(:created_at)
  end

  def build_resource_params
    [params.fetch(:work_history, {}).permit(%i(
      company
      industry
      industry_other
      from_date
      to_date
      current
      position
      summary ))]
  end
end

app/views/work_histories/_form_nav.html.haml
=link_to t('back.education_histories'), professional_profile_education_histories_path(@professional_profile), class: "link--formNav left"

app/views/work_histories/index.html.haml
.professionalProfile
  = render partial: '/professional_header', locals: { profile_piece: @professional_profile }

  %section.container
    = render "layouts/profile_sidebar"
    %section.mainContent--form
      %section.formWrapper
        %section.formNav--small
          = render "form_nav"
        %header.formHeader
          %h3.formHeader__title
            =t('views.work_histories.nav_title')
          %section.formHeader__action
            = link_to omniauth_authorize_path(current_user, :linkedin, state: current_user, limit_to: "work_history"), class: "button--linkedinSmall js--buttonWorking" do
              %span.button__icon
              %span.button__text= t('linkedin.import')
            %span.legal
              = t('linkedin.tooltip.import')

        %section.formHelp
          %h4=t("views.work_histories.help_title")
          %p=t("views.work_histories.help_text")

        %section.formEntry
          = simple_form_for WorkHistory.new, url: professional_profile_work_histories_path,  html: { class: 'js-dirty-check', data: {analytics: "submit-work"}  } do |f|
            %section.formBlock
              %section.formBlock__section--full
                = f.input :company,
                          label_html: {class: "label--standard"},
                          wrapper_html: {class: "inputWrapper--fifth"}

                = f.input :position,
                          label_html: {class: "label--standard"},
                          wrapper_html: {class: "inputWrapper--fifth"}

                = f.input :from_date,
                          use_short_month: true,
                          discard_day: true,
                          start_year: Time.now.year - 60,
                          end_year: Time.now.year,
                          placeholder: "Pick the start date",
                          wrapper_html: {class: "inputWrapper--fifth"},
                          input_html: {class: "date-picker inputWrapper--inner"},
                          label_html: {class: "label--standard"},
                          order: [:month, :year]
                = f.input :to_date,
                          use_short_month: true,
                          discard_day: true,
                          start_year: Time.now.year - 60,
                          end_year: Time.now.year,
                          placeholder: "Pick the end date",
                          wrapper_html: {class: "inputWrapper--fifth"},
                          input_html: {class: "date-picker inputWrapper--inner"},
                          label_html: {class: "label--standard"},
                          order: [:month, :year]

                = f.input :current,
                          wrapper_html: {class: "inputWrapper--fifth inputWrapper--omega"},
                          label_html: {class: "label--standard"},
                          input_html: {class: "js-current-history"}

                = f.input :summary,
                          label_html: {class: "label--standard"}

            %section.formBlock__save
              %section.formBlock__section--action
                = f.submit t("views.work_histories.add_entry"), class: "button--small"

        %section.formBlock__section--full
          - @professional_profile.work_histories.each do |wh|
            - if wh.summary
              .historyEntry--withSummary
                %section.historyEntry__section
                  %strong=wh.company
                %section.historyEntry__section=wh.position
                %section.historyEntry__section
                  %span=text("time_span", start: wh.try(:from_date).try(:strftime, "%b %Y"), end: wh.try(:to_date).try(:strftime, "%b %Y") || "present")
                %section.historyEntry__section.text-right=link_to t("views.work_histories.delete_entry"),
                  professional_profile_work_history_path(@professional_profile, wh), class: "link--delete", method: :delete
                %section.historyEntry__jobSummary=wh.summary
            - else
              .historyEntry
                %section.historyEntry__section
                  %strong=wh.company
                %section.historyEntry__section=wh.position
                %section.historyEntry__section
                  %span=text("time_span", start: wh.try(:from_date).try(:strftime, "%b %Y"), end: wh.try(:to_date).try(:strftime, "%b %Y") || "present")
                %section.historyEntry__section.text-right=link_to t("views.work_histories.delete_entry"),
                  professional_profile_work_history_path(@professional_profile, wh), class: "link--delete", method: :delete

        %section.formBlock
          %section.formBlock__section--action
            = render "form_nav"